name: Test

on: [push, pull_request]

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get Vercel Preview URL
        uses: ViktorJT/Get-Vercel-preview-url-by-commit-SHA-action@main
        with:
          vercel_access_token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
