name: 'Get Vercel Preview URL'
description: 'Get the preview URL of a Vercel deployment'
branding:
  icon: link
  color: gray-dark

inputs:
  vercel_team_id:
    description: 'https://vercel.com/docs/rest-api#introduction/api-basics/authentication/accessing-resources-owned-by-a-team'
    required: true
  vercel_access_token:
    description: 'https://vercel.com/docs/rest-api#introduction/api-basics/authentication/creating-an-access-token'
    required: true
  timeout:
    description: 'Time spent waiting between requests to the Vercel Api'
    default: 3000

outputs:
  preview_url:
    description: 'Vercel deployment preview URL'

runs:
  using: 'node16'
  main: 'dist/index.js'
